### PR TITLE
Support GHC 9 and add Github Actions

### PR DESCRIPTION
**Pull request by adamgundry**
Simplified subsumption broke precisely one definition. I plan to release a fix as 0.1.1.4 and retroactively add upper bounds on `base` for previous releases.

### CODE REVIEW

**Comment by adamgundry** [comment]
Release candidate: https://hackage.haskell.org/package/units-parser-0.1.1.4/candidate

**Review by goldfirere — APPROVED** [review]
I know nothing of setting up CI on GitHub, but the code change is easy enough to review. :)

**Comment by philderbeast** [comment]
Can this be merged?

**Comment by adamgundry** [comment]
Thanks for the prod @philderbeast, I see I never quite got to pushing the buttons here, sorry! Will merge and release.

**Comment by philderbeast** [comment]
Fantastic thanks @adamgundry, this new `0.1.1.4` version from hackage is working for me with `ghc-9.0.1`.

**Pull request merged**
